### ISSUE TITLE
ERROR [io.undertow.request] (default I/O-16) Closing SSLConduit after exception on handshake: javax.net.ssl.SSLHandshakeException: null cert chain

### ISSUE THREAD

**Issue by dinbtechit** [dinbtechit/two-way-ssl-btw-apache-widlfly19-elytron#1]
**Wildfly server.log:**

```
2020-04-15 15:29:50,238 [ :  :  :  : ]  ERROR [io.undertow.request] (default I/O-16) Closing SSLConduit after exception on handshake: javax.net.ssl.SSLHandshakeException: null cert chain
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:802)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766)
        at io.undertow.protocols.ssl.ALPNHackSSLEngine.unwrap(ALPNHackSSLEngine.java:265)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.undertow.server.protocol.http.ALPNLimitingSSLEngine.unwrap(ALPNLimitingSSLEngine.java:75)
        at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:757)
        at io.undertow.protocols.ssl.SslConduit.doHandshake(SslConduit.java:648)
        at io.undertow.protocols.ssl.SslConduit.access$900(SslConduit.java:63)
        at io.undertow.protocols.ssl.SslConduit$5$1.run(SslConduit.java:1084)
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
Caused by: javax.net.ssl.SSLHandshakeException: null cert chain
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:306)
        at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1939)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:232)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
        at io.undertow.protocols.ssl.SslConduit$5.run(SslConduit.java:1072)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by dinbtechit** [comment]
This is basically means wildfly server is not able to confirm if the request is coming from the actual Apache Server. 

Ensure you have this configuration in Apache. (Note: Provided Apache's public cert was already added to Wildfly's trust store.)

Apache Conf:
``` apacheconf
SSLProxyMachineCertificateFile /etc/certs/selfSigned/apache_proxy.pem
```

You'll also see this error in Apache's ssl_error logs:
```
Wed Apr 15 15:29:50.236667 2020] [ssl:warn] [pid 36165:tid 140473289303808] AH02268: Proxy client certificate callback: (apache-localhost:443) downstream server wanted client certificate but none are configured
[Wed Apr 15 15:29:50.239257 2020] [proxy_http:error] [pid 36165:tid 140473289303808] (103)Software caused connection abort: [client 172.17.0.1:51034] AH01102: error reading status line from remote server wildfly-localhost:8443, referer: https://localhost/

```
